[package]
name = "jiaxin2006-tg-rcore-tutorial-sbi-t4"
description = "Custom T4 SBI fork for rCore tutorial OS: timer forwarding and SMP bring-up support."
version = "0.0.4-preview.1"
edition = "2024"
authors = ["Jiaxin Han <hanjx23@mails.tsinghua.edu.cn>"]
repository = "https://github.com/Jiaxin2006/tg-rcore-tutorial"
homepage = "https://github.com/Jiaxin2006/tg-rcore-tutorial/tree/test/tg-rcore-tutorial-sbi"
documentation = "https://docs.rs/jiaxin2006-tg-rcore-tutorial-sbi-t4"
license = "GPL-3.0"
readme = "README.md"
keywords = ["rcore", "sbi", "no-std", "riscv"]
categories = ["no-std", "embedded"]

[features]
default = []
nobios = []

[package.metadata.docs.rs]
targets = ["riscv64gc-unknown-none-elf"]

[dependencies]
