# Build Doom for rCore (RISC-V 64-bit, bare-metal with custom libc).
#
# Usage:
#   make -f Makefile.rcore
#   # produces: doomgeneric  (ELF binary to be packed into fs.img by build.rs)

RISCV_PREFIX ?= riscv64-elf-
DG_MODE ?= interactive
CC  = $(RISCV_PREFIX)gcc
AS  = $(RISCV_PREFIX)gcc
LD  = $(RISCV_PREFIX)gcc
OBJCOPY = $(RISCV_PREFIX)objcopy

GCC_INCDIR := $(shell $(CC) -print-file-name=include)

CFLAGS  = -march=rv64gc -mabi=lp64d -O2 -g -std=gnu11
CFLAGS += -ffreestanding -nostdinc
CFLAGS += -isystem $(GCC_INCDIR)
CFLAGS += -isystem rcore_include
CFLAGS += -I.
CFLAGS += -Wall -Wno-unused-variable -Wno-unused-function -Wno-unused-but-set-variable
CFLAGS += -DNORMALUNIX -DLINUX -D_DEFAULT_SOURCE

ifeq ($(DG_MODE),interactive)
CFLAGS += -DDG_RCORE_INTERACTIVE=1
endif

ASFLAGS = -march=rv64gc -mabi=lp64d

LDFLAGS = -march=rv64gc -mabi=lp64d
LDFLAGS += -nostartfiles -nostdlib -static
LDFLAGS += -T rcore.ld
LDFLAGS += -Wl,--gc-sections

OBJDIR = build_rcore
OUTPUT = doomgeneric

# Doom source objects (same list as upstream Makefile, replace xlib with rcore)
SRC_DOOM = dummy.o am_map.o doomdef.o doomstat.o dstrings.o \
	d_event.o d_items.o d_iwad.o d_loop.o d_main.o d_mode.o d_net.o \
	f_finale.o f_wipe.o g_game.o hu_lib.o hu_stuff.o info.o \
	i_cdmus.o i_endoom.o i_joystick.o i_scale.o i_sound.o i_system.o \
	i_timer.o memio.o m_argv.o m_bbox.o m_cheat.o m_config.o \
	m_controls.o m_fixed.o m_menu.o m_misc.o m_random.o \
	p_ceilng.o p_doors.o p_enemy.o p_floor.o p_inter.o p_lights.o \
	p_map.o p_maputl.o p_mobj.o p_plats.o p_pspr.o p_saveg.o \
	p_setup.o p_sight.o p_spec.o p_switch.o p_telept.o p_tick.o p_user.o \
	r_bsp.o r_data.o r_draw.o r_main.o r_plane.o r_segs.o r_sky.o r_things.o \
	sha1.o sounds.o statdump.o st_lib.o st_stuff.o s_sound.o \
	tables.o v_video.o wi_stuff.o w_checksum.o w_file.o w_main.o w_wad.o \
	z_zone.o w_file_stdc.o i_input.o i_video.o doomgeneric.o \
	doomgeneric_rcore.o

# rCore support objects
SRC_RCORE = rcore_crt0.o rcore_libc.o

OBJS  = $(addprefix $(OBJDIR)/, $(SRC_RCORE))
OBJS += $(addprefix $(OBJDIR)/, $(SRC_DOOM))

LIBS = -lgcc

all: $(OUTPUT)

clean:
	rm -rf $(OBJDIR) $(OUTPUT)

$(OUTPUT): $(OBJS)
	@echo "[CFG] DG_MODE=$(DG_MODE)"
	@echo "[LD] $@"
	$(LD) $(LDFLAGS) $(OBJS) -o $@ $(LIBS)
	@echo "[SIZE]"
	-$(RISCV_PREFIX)size $@

$(OBJS): | $(OBJDIR)

$(OBJDIR):
	mkdir -p $(OBJDIR)

$(OBJDIR)/%.o: %.S
	@echo "[AS] $<"
	$(AS) $(ASFLAGS) -c $< -o $@

$(OBJDIR)/%.o: %.c
	@echo "[CC] $<"
	$(CC) $(CFLAGS) -c $< -o $@

.PHONY: all clean
